[zh_en_ass]
language = "zh_en"

format = "ASS"

header = '''
[Script Info]
Title: Default ASS file
ScriptType: v4.00+
WrapStyle: 2
Collisions: Normal
PlayResX: 1280
PlayResY: 720
ScaledBorderAndShadow: yes
Video Zoom Percent: 1

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding

Style: ZH,方正兰亭中粗黑_GBK,35,&H00FFFFFF,&H00FFFFFF,&H19533B3B,&H910E0807,0,0,0,0,100.0,100.0,0.0,0.0,1,2.1538463,1.2,2,135,135,53,1
Style: EN,Segoe UI Semibold,32,&H00FFFFFF,&H00FFFFFF,&H19120D0D,&H910E0807,0,0,0,0,100.0,100.0,0.0,0.0,1,1.5769231,0.0,2,135,135,14,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text'''

zh_line = 'Dialogue: 2,0:00:00.00,0:00:00.00,ZH,NTP,0,0,0,,'

en_line = 'Dialogue: 1,0:00:00.00,0:00:00.00,EN,NTP,0,0,0,,'


[en_zh_ass]
language = "en_zh"

format = "ASS"

header = '''
[Script Info]
; Script generated by Arctime Pro 2.4
; http://arctime.cn/
Title: Default ASS file
ScriptType: v4.00+
WrapStyle: 2
Collisions: Normal
PlayResX: 1280
PlayResY: 720
ScaledBorderAndShadow: yes
Video Zoom Percent: 1

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: ZH,方正兰亭中粗黑_GBK,31,&H00FFFFFF,&H00FFFFFF,&H19533B3B,&H910E0807,0,0,0,0,100.0,100.0,0.0,0.0,1,1.7692308,1.2,2,135,135,7,1
Style: EN,Segoe UI Semibold,44,&H00FFFFFF,&H00FFFFFF,&H19120D0D,&H910E0807,0,0,0,0,100.0,100.0,0.0,0.0,1,2.5384617,0.0,2,135,135,55,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text'''

en_line = 'Dialogue: 2,0:00:00.00,0:00:00.00,EN,NTP,0,0,0,,'

zh_line = 'Dialogue: 1,0:00:00.00,0:00:00.00,ZH,NTP,0,0,0,,'